on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.1

      - name: Install dependencies
        run: npm install
        working-directory: ./edicolab-pi.github.io # Set this to your Docusaurus directory

      - name: Build site
        run: npm run build
        working-directory: ./edicolab-pi.github.io # Set this to your Docusaurus directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./edicolab-pi.github.io/build # Adjust the path if needed
